# version: '3.9' - used in lab, but it gives a warning and says please remove so I commented it out
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm start' #TODO: change the command to `npm run testandrun` to run mocha, change back to 'npm start' after running mocha
volumes:
  group-project: